# Generated by Django 2.2.7 on 2019-11-06 13:33

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUser',
            fields=[
                ('pk_core_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_photo', models.ImageField(blank=True, default='images/user.png', upload_to=apps.core.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
            },
        ),
    ]
