# Generated by Django 2.2.7 on 2019-11-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDevices',
            fields=[
                ('pk_devices', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mac do Dispositivo')),
                ('descr_device', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ga_nas_id', models.CharField(max_length=50, verbose_name='Ident. Diálogo')),
                ('ga_srvr', models.CharField(max_length=64, verbose_name='Ip do AP')),
                ('ga_loc', models.CharField(max_length=64, verbose_name='Localização')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Autenticadores',
                'db_table': 'core_server_devices',
            },
        ),
        migrations.CreateModel(
            name='TypeDevice',
            fields=[
                ('pk_types_device', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descr_device', models.CharField(max_length=100, verbose_name='Descrição')),
                ('supply_device', models.CharField(max_length=50, verbose_name='Marca')),
                ('model_device', models.CharField(max_length=50, verbose_name='Modelo')),
                ('flag_approve', models.BooleanField(default=False, verbose_name='Homologado')),
                ('field_map_device_params', models.TextField(default='{"ga_ssid": "identity", "ga_ap_mac": "mac do ap", "ga_nas_id": "chap-id", "ga_srvr": "server-address", "ga_cmac": "mac", "ga_cip": "ip", "ga_loc": "", "ga_Qv": "chap-challenge", "link-login": "link-login", "link-orig": "link-orig", "link-login-only": "link-login-only", "link-orig-esc": "link-orig-esc"}', verbose_name='Parâmetros')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tipos de Dispositivos',
                'db_table': 'core_types_device',
            },
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('pk_user_devices', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Dispositivo')),
                ('mac_address', models.CharField(max_length=15, unique=True, verbose_name='Endereço Mac')),
                ('ga_ssid', models.CharField(max_length=64, verbose_name='SSID conexão')),
                ('ga_cmac', models.CharField(max_length=15, verbose_name='Mac Cliente')),
                ('ga_cip', models.CharField(max_length=15, verbose_name='IP Cliente')),
                ('ga_Qv', models.CharField(max_length=128, verbose_name='autenticador')),
                ('link_login', models.CharField(max_length=128, verbose_name='Link Login')),
                ('link_orig', models.CharField(max_length=128, verbose_name='Link Original')),
                ('link_login_only', models.CharField(max_length=128, verbose_name='Link Login Author')),
                ('link_orig_esc', models.CharField(max_length=128, verbose_name='Link de Redirecionamento')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('fk_server_devices', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ServerDevices')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.CoreUser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Dispositivos',
                'db_table': 'core_user_devices',
            },
        ),
        migrations.AddField(
            model_name='serverdevices',
            name='fk_types_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TypeDevice', verbose_name='Tipo'),
        ),
    ]
